services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: app
    restart: unless-stopped
    container_name: symfony-app-task 
    depends_on:
      - db 
    ports:
      - "9980:80" 
    volumes:
      - .:/var/www/project 
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf:ro 
      - ./.bashrc:/root/.bashrc:ro 
      - ./data:/mnt/data
  db:
    image: mysql:8.4
    restart: unless-stopped 
    container_name: "symfony-db"
    volumes:
      - mysql_data:/var/lib/mysql 
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: app_task
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: task_db
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    container_name: "symfony-pma"
    ports:
      - "9981:80" 
    depends_on:
      - db
    environment:
      PMA_HOST: db 
      PMA_USER: app_task 
      PMA_PASSWORD: test 

volumes:
  mysql_data:
